import Head from "next/head"
import SignupForm from "../components/SignupForm"

export default function Home() {
  const menuItems = ["React", "Node.js", "MongoDB"]

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-black/20 backdrop-blur-sm">
        <nav className="grid grid-cols-2 sm:flex justify-between items-center text-white max-w-screen-xl mx-auto">
          <a
            href=""
            className="hover:bg-purple-800/60 min-h-[3rem] px-4 inline-flex items-center justify-self-start"
          >
            Logo
          </a>

          <input
            type="checkbox"
            className="peer sm:hidden appearance-none justify-self-end min-h-[3rem] px-3 inline-flex items-center text-3xl after:content-['≡'] checked:after:content-['×']"
            aria-controls="navigation-menu"
            aria-label="Toggle navigation menu"
          />

          <ul
            className="hidden sm:flex flex-col sm:gap-8 sm:flex-row peer-checked:flex col-start-1 col-end-3"
            id="navigation-menu"
          >
            {menuItems.map((item, index) => (
              <li key={index}>
                <a
                  href=""
                  className="hover:bg-fuchsia-700/20 min-h-[3rem] px-4 inline-flex items-center"
                >
                  {item}
                </a>
              </li>
            ))}
          </ul>
        </nav>
      </div>

      <main>
        <div className="max-w-max bg-black/20 backdrop-blur-sm p-12 mx-auto mt-4 rounded-lg text-lg">
          <h1 className="mb-6 bg-clip-text text-transparent text-6xl font-bold bg-gradient-to-l from-pink-500 to-violet-500">
            Full Stack Mini
          </h1>

          <div className="text-white">
            <p className="mb-4">
              Darmowy mini kurs tworzenia Full Stack’owej aplikacji
            </p>
            <p className="mb-4">W ciągu 7 dni:</p>
            <ul className="list-disc list-inside mb-8">
              <li>Stworzysz stronę taką jak ta z użyciem Reacta</li>
              <li>Użyjesz TailwindCSS do ostylowania wyglądu</li>
              <li>Poznasz backendowe środowisko Node.js</li>
              <li>Użyjesz Reactowego frameworka Next.js</li>
              <li>Zapiszesz dane z formularza w bazie MongoDB</li>
              <li>Użyjesz Prismy dla ułatwienia kontaktu z bazą</li>
              <li>Stworzysz repozytorium Git na GitHubie</li>
              <li>Umieścisz swoją aplikację w internecie</li>
            </ul>
          </div>

          <SignupForm />
        </div>
      </main>
    </div>
  )
}
